// voluntariado-frontend/src/components/EmergencyDetailComponent.vue
<template>
    <div>
        <h1>Emergencia : {{ $route.params.id }}</h1>
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Cantidad de voluntarios requeridos</th>
                    <th>Cantidad de voluntarios inscritos</th>
                    <th>Id de emergencia</th>
                    <th>Fecha de inicio</th>
                    <th>Fecha de fin</th>
                    <th>Id de estado</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="tarea in emergency" :key="tarea.id">
                    <td>{{ tarea.id }}</td>
                    <td>{{ tarea.nombre }}</td>
                    <td>{{ tarea.descrip }}</td>
                    <td>{{ tarea.cant_vol_requeridos }}</td>
                    <td>{{ tarea.cant_vol_inscritos }}</td>
                    <td>{{ tarea.id_emergencia }}</td>
                    <td>{{ tarea.finicio }}</td>
                    <td>{{ tarea.ffin }}</td>
                    <td>{{ tarea.id_estado }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<script>
export default {
    name: 'Emergencia',
    data() {
        return {
            emergency: []

        };
    },
    mounted() {
        this.fetchUsers();
    },
    methods: {
        async fetchUsers() {
            const response = await fetch('http://localhost:8080/tarea/byemergencia/' + this.$route.params.id);
            const data = await response.json();
            this.emergency = data;
        }
    }
}
</script>

// voluntariado-frontend-react/src/component/EmergencyDetail.jsx
import React, { useEffect, useState } from 'react'
import axios from 'axios'
export default function EmergencyDetail(props) {
    const [data, setData] = useState([]);
    useEffect(() => {
        axios.get(`http://localhost:8080/tarea/byemergencia/${props.id}`)
            .then((res) => {
                setData(res.data)
            })
    })
    return (
        <table class="table">
            <thead>
                <tr>
                    <th scope='col'>ID</th>
                    <th scope='col'>Nombre</th>
                    <th scope='col'>Descripción</th>
                    <th scope='col'>Cantidad de Voluntarios Requeridos</th>
                    <th scope='col'>ID de Emergencia</th>
                    <th scope='col'>Fecha de Inicio</th>
                    <th scope='col'>Fecha de Fin</th>
                    <th scope='col'>ID de Estado</th>
                    <th scope='col'>Cantidad de Voluntarios Inscritos</th>
                </tr>
            </thead>
            <tbody>
                {data.map((item) => (
                    <tr key={item.id}>
                        <td scope='row'>{item.id}</td>
                        <td>{item.nombre}</td>
                        <td>{item.descrip}</td>
                        <td>{item.cant_vol_requeridos}</td>
                        <td>{item.id_emergencia}</td>
                        <td>{item.finicio}</td>
                        <td>{item.ffin}</td>
                        <td>{item.id_estado}</td>
                        <td>{item.catn_vol_inscritos}</td>
                    </tr>
                ))}
            </tbody>
        </table>
    )
}
